/**
 * Story Narrator Cloud Run Server
 * HTTP API for multi-character voice synthesis
 */

require('dotenv').config();

const http = require('http');
const url = require('url');

const { createResilientTTSClient } = require('./resilient-tts-client');

const PORT = process.env.PORT || 8080;

const ttsClient = createResilientTTSClient({
  elevenlabsKey: process.env.ELEVENLABS_API_KEY,
  sarvamKey: process.env.SARVAM_API_KEY,
  googleKey: process.env.GOOGLE_TTS_API_KEY,
  minimaxKey: process.env.MINIMAX_API_KEY
});

let orchestrator = null;

function getOrchestrator() {
  if (!orchestrator) {
    const { StoryOrchestrator } = require('./orchestrator/story-orchestrator');
    const OpenAI = require('openai');
    const openai = new OpenAI({
      apiKey: 'csk-2jdpd54822wcdyhv2h3c5h6n4vwk8fj6vrefkfhmh2r552we',
      baseURL: 'https://api.cerebras.net/v1'
    });
    orchestrator = new StoryOrchestrator(openai, { language: 'hinglish' });
  }
  return orchestrator;
}

const speakerMap = {
  'NARRATOR': 'anushka',
  'MALE': 'karun',
  'FEMALE': 'vidya'
};

async function handleGenerateStory(req, res, body) {
  try {
    const { theme, setting, plotOutline, characters } = body;

    if (!theme) {
      res.writeHead(400, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Missing theme parameter' }));
      return;
    }

    const story = await getOrchestrator().autoGenerateStory({ theme, setting, plotOutline });

    res.writeHead(200, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({
      success: true,
      storyId: story.id,
      theme: story.theme,
      segmentCount: story.segments.filter(s => s.type === 'dialogue').length,
      characters: story.characters.map(c => ({
        name: c.name,
        role: c.role,
        personality: c.personality,
        speechPattern: c.speechPattern,
        quirks: c.quirks
      }))
    }));

    getOrchestrator().cleanupAutoGenerated();

  } catch (error) {
    console.error('Story generation error:', error);
    res.writeHead(500, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: error.message }));
  }
}

async function handleSynthesize(req, res, body) {
  try {
    const { text, voice = 'NARRATOR', language = 'en' } = body;

    if (!text) {
      res.writeHead(400, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Missing text parameter' }));
      return;
    }

    const audio = await ttsClient.synthesize(text, { voice, language });

    res.writeHead(200, {
      'Content-Type': 'audio/wav',
      'Content-Length': audio.length
    });
    res.end(audio);

  } catch (error) {
    console.error('TTS synthesis error:', error);
    res.writeHead(500, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: error.message }));
  }
}

async function handleHealth(req, res) {
  const ttsStatus = ttsClient.getStatus();

  res.writeHead(200, { 'Content-Type': 'application/json' });
  res.end(JSON.stringify({
    status: 'healthy',
    service: 'story-narrator',
    timestamp: new Date().toISOString(),
    ttsProviders: ttsStatus.providers
  }));
}

async function handleNarrate(req, res, body) {
  try {
    const { source, content, url, voice = 'NARRATOR', language = 'en' } = body;
    console.log('[Narrate] body:', JSON.stringify(body));

    let textToNarrate = content || '';

    if (url) {
      textToNarrate = await fetchContentFromUrl(url);
    }

    if (!textToNarrate) {
      res.writeHead(400, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'No content to narrate' }));
      return;
    }

    const audio = await ttsClient.synthesize(textToNarrate, { voice, language });

    res.writeHead(200, {
      'Content-Type': 'audio/wav',
      'Content-Length': audio.length
    });
    res.end(audio);

  } catch (error) {
    console.error('Narrate error:', error);
    res.writeHead(500, { 'Content-Type': 'application/json' });
    res.end(JSON.stringify({ error: error.message }));
  }
}

async function fetchContentFromUrl(targetUrl) {
  const urlLower = targetUrl.toLowerCase();

  if (urlLower.includes('twitter.com') || urlLower.includes('x.com')) {
    return `[NARRATOR] This is a Twitter thread. In this story, the main character shares their experience. [PAUSE: 1s] ${getOrchestrator().autoGenerateStory({ theme: 'A person shares their story on social media' })}`;
  }

  if (urlLower.includes('wa.me') || urlLower.includes('whatsapp')) {
    return '[NARRATOR] A WhatsApp conversation unfolds between friends discussing an important matter.';
  }

  const { URL } = require('url');
  const parsed = new URL(targetUrl);
  const https = require('https');

  return new Promise((resolve, reject) => {
    const options = {
      hostname: parsed.hostname,
      path: parsed.pathname,
      method: 'GET',
      headers: { 'User-Agent': 'Mozilla/5.0' }
    };

    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', chunk => data += chunk);
      res.on('end', () => {
        const text = data.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim();
        resolve(text.substring(0, 2000));
      });
    });

    req.on('error', reject);
    req.end();
  });
}

const server = http.createServer(async (req, res) => {
  const parsedUrl = url.parse(req.url, true);
  const pathname = parsedUrl.pathname;

  const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type'
  };

  if (req.method === 'OPTIONS') {
    res.writeHead(204, corsHeaders);
    res.end();
    return;
  }

  let body = '';
  req.on('data', chunk => body += chunk);
  req.on('end', async () => {
    try {
      if (body) {
        body = JSON.parse(body);
      }
    } catch (e) {
      body = {};
    }

    if (pathname === '/health' && req.method === 'GET') {
      await handleHealth(req, res);
    } else if (pathname === '/generate' && req.method === 'POST') {
      await handleGenerateStory(req, res, body);
    } else if (pathname === '/synthesize' && req.method === 'POST') {
      await handleSynthesize(req, res, body);
    } else if (pathname === '/narrate' && req.method === 'POST') {
      await handleNarrate(req, res, body);
    } else {
      res.writeHead(404, { 'Content-Type': 'application/json' });
      res.end(JSON.stringify({ error: 'Not found' }));
    }
  });
});

server.listen(PORT, () => {
  console.log(`[Story Narrator] Server running on port ${PORT}`);
  console.log('[Story Narrator] Endpoints:');
  console.log('  GET  /health     - Health check');
  console.log('  POST /generate   - Generate story with auto-characters');
  console.log('  POST /synthesize - Convert text to speech');
  console.log('  POST /narrate    - Narrate from text/URL (Twitter, WhatsApp, etc)');
});

module.exports = server;